backend:
  name: git-gateway
  branch: live

publish_mode: editorial_workflow
media_folder: static/uploads
public_folder: /uploads

locale: "pt"

collections:
  - name: "posts"
    label: "Posts"
    folder: "static/posts"
    create: true
    fields:
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

