backend:
  name: git-gateway
  branch: live

publish_mode: editorial_workflow
media_folder: static/uploads
public_folder: /uploads

locale: "pt"

collections:
  - name: "services"
    label: "Serviços"
    folder: "static/services"
    create: true
    fields:
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Corpo", name: "body", widget: "markdown" }
  - name: "clients"
    label: "Clientes"
    folder: "static/clients"
    create: true
    fields:
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Nome", name: "title", widget: "string" }
      - { label: "Logo", name: "logo", widget: "image" }
      - { label: "Localização", name: "location", widget: "map" }
      - { label: "Descrição", name: "body", widget: "markdown" }
